import { useEffect, useState } from "react";
import type { DailyEntry, ReportReason, Synthesis } from "../lib/types";
import { submitContentReport } from "../lib/api";

const REASONS: { value: ReportReason; label: string; hint: string }[] = [
  {
    value: "offensive",
    label: "Offensive or demeaning",
    hint: "Hateful, abusive, or degrading language",
  },
  {
    value: "harmful_guidance",
    label: "Spiritually harmful",
    hint: "Pushes something damaging, manipulative, or presumptuous",
  },
  {
    value: "scripture_error",
    label: "Scripture is wrong",
    hint: "Misquoted, mis-referenced, or used against its meaning",
  },
  {
    value: "nonsense",
    label: "Incoherent",
    hint: "Doesn't make sense or is clearly broken",
  },
  { value: "other", label: "Something else", hint: "Tell us below" },
];

type Props =
  | { entry: DailyEntry; synthesis?: never }
  | { synthesis: Synthesis; entry?: never };

/**
 * In-app reporting for AI-generated content.
 *
 * Required by Google Play's Generative AI policy: users must be able to flag
 * offensive output without leaving the app. Kept deliberately quiet in the
 * layout — always reachable, never competing with the content itself.
 */
export default function ReportButton(props: Props) {
  const [open, setOpen] = useState(false);
  const [reason, setReason] = useState<ReportReason | null>(null);
  const [detail, setDetail] = useState("");
  const [saving, setSaving] = useState(false);
  const [done, setDone] = useState(false);
  const [error, setError] = useState("");

  // Close on Escape — the sheet traps attention, so give an obvious way out.
  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => e.key === "Escape" && close();
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [open]);

  function close() {
    setOpen(false);
    setError("");
    if (done) {
      // reset only after a successful submission has been acknowledged
      setDone(false);
      setReason(null);
      setDetail("");
    }
  }

  async function submit() {
    if (!reason) return;
    setSaving(true);
    setError("");
    try {
      if (props.entry) {
        await submitContentReport({
          target: "daily_entry",
          entry: props.entry,
          reason,
          detail,
        });
      } else {
        await submitContentReport({
          target: "synthesis",
          synthesis: props.synthesis,
          reason,
          detail,
        });
      }
      setDone(true);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Could not send report");
    } finally {
      setSaving(false);
    }
  }

  return (
    <>
      <button
        onClick={() => setOpen(true)}
        className="pressable min-h-[44px] text-xs font-semibold uppercase tracking-[0.14em] text-muted underline underline-offset-4"
      >
        Report this content
      </button>

      {open && (
        <div
          className="fixed inset-0 z-50 flex items-end justify-center bg-ink/40 sm:items-center"
          role="dialog"
          aria-modal="true"
          aria-label="Report this content"
          onClick={close}
        >
          <div
            className="max-h-[88vh] w-full overflow-y-auto rounded-t-2xl bg-paper p-6 sm:max-w-md sm:rounded-2xl"
            onClick={(e) => e.stopPropagation()}
          >
            {done ? (
              <div>
                <h2 className="font-display text-2xl">Thank you</h2>
                <p className="mt-3 text-[15px] leading-relaxed text-ink/90">
                  Your report has been recorded. This content is generated, and
                  flagging it helps catch what shouldn't have been written.
                </p>
                <p className="mt-3 text-[15px] leading-relaxed text-ink/90">
                  If something here has left you distressed, please talk to
                  someone you trust — a pastor, a friend, or a counsellor.
                </p>
                <button
                  onClick={close}
                  className="pressable mt-6 min-h-[44px] w-full rounded-xl bg-ink text-sm font-semibold text-paper"
                >
                  Close
                </button>
              </div>
            ) : (
              <>
                <h2 className="font-display text-2xl">Report this content</h2>
                <p className="mt-2 text-[15px] leading-relaxed text-muted">
                  This devotional was generated by AI. Tell us what's wrong with
                  it.
                </p>

                <fieldset className="mt-5 space-y-2">
                  <legend className="sr-only">Reason</legend>
                  {REASONS.map((r) => (
                    <label
                      key={r.value}
                      className={`flex cursor-pointer gap-3 rounded-xl border p-3.5 ${
                        reason === r.value
                          ? "border-moss bg-moss-soft"
                          : "border-hairline bg-surface"
                      }`}
                    >
                      <input
                        type="radio"
                        name="report-reason"
                        value={r.value}
                        checked={reason === r.value}
                        onChange={() => setReason(r.value)}
                        className="mt-1 accent-moss"
                      />
                      <span>
                        <span className="block text-[15px] font-semibold">
                          {r.label}
                        </span>
                        <span className="block text-[13px] leading-snug text-muted">
                          {r.hint}
                        </span>
                      </span>
                    </label>
                  ))}
                </fieldset>

                <textarea
                  value={detail}
                  onChange={(e) => setDetail(e.target.value.slice(0, 2000))}
                  rows={3}
                  placeholder="Anything else we should know? (optional)"
                  className="mt-4 w-full resize-none rounded-xl border border-hairline bg-surface px-4 py-3 text-[15px] leading-relaxed outline-none focus:border-moss"
                />

                {error && <p className="mt-2 text-sm text-rust">{error}</p>}

                <div className="mt-5 flex gap-3">
                  <button
                    onClick={close}
                    className="pressable min-h-[44px] flex-1 rounded-xl border border-hairline text-sm font-semibold"
                  >
                    Cancel
                  </button>
                  <button
                    onClick={submit}
                    disabled={!reason || saving}
                    className="pressable min-h-[44px] flex-1 rounded-xl bg-ink text-sm font-semibold text-paper disabled:opacity-40"
                  >
                    {saving ? "Sending…" : "Send report"}
                  </button>
                </div>
              </>
            )}
          </div>
        </div>
      )}
    </>
  );
}
