// Canonical 66-book list for the World English Bible.
// `file` matches the JSON filenames in the `world-english-bible` npm package.
// `aliases` are lowercase; used by resolve_verse_ref() for reference parsing.

export const BOOKS = [
  { n: 1,  file: 'genesis',         name: 'Genesis',         testament: 'OT', aliases: ['gen', 'ge', 'gn'] },
  { n: 2,  file: 'exodus',          name: 'Exodus',          testament: 'OT', aliases: ['exo', 'ex', 'exod'] },
  { n: 3,  file: 'leviticus',       name: 'Leviticus',       testament: 'OT', aliases: ['lev', 'le', 'lv'] },
  { n: 4,  file: 'numbers',         name: 'Numbers',         testament: 'OT', aliases: ['num', 'nu', 'nm', 'nb'] },
  { n: 5,  file: 'deuteronomy',     name: 'Deuteronomy',     testament: 'OT', aliases: ['deut', 'dt', 'de'] },
  { n: 6,  file: 'joshua',          name: 'Joshua',          testament: 'OT', aliases: ['josh', 'jos', 'jsh'] },
  { n: 7,  file: 'judges',          name: 'Judges',          testament: 'OT', aliases: ['judg', 'jdg', 'jg', 'jdgs'] },
  { n: 8,  file: 'ruth',            name: 'Ruth',            testament: 'OT', aliases: ['rth', 'ru'] },
  { n: 9,  file: '1samuel',         name: '1 Samuel',        testament: 'OT', aliases: ['1 sam', '1sam', '1 sa', 'i samuel', 'first samuel'] },
  { n: 10, file: '2samuel',         name: '2 Samuel',        testament: 'OT', aliases: ['2 sam', '2sam', '2 sa', 'ii samuel', 'second samuel'] },
  { n: 11, file: '1kings',          name: '1 Kings',         testament: 'OT', aliases: ['1 kgs', '1kgs', '1 ki', 'i kings', 'first kings'] },
  { n: 12, file: '2kings',          name: '2 Kings',         testament: 'OT', aliases: ['2 kgs', '2kgs', '2 ki', 'ii kings', 'second kings'] },
  { n: 13, file: '1chronicles',     name: '1 Chronicles',    testament: 'OT', aliases: ['1 chron', '1chron', '1 chr', '1 ch', 'i chronicles', 'first chronicles'] },
  { n: 14, file: '2chronicles',     name: '2 Chronicles',    testament: 'OT', aliases: ['2 chron', '2chron', '2 chr', '2 ch', 'ii chronicles', 'second chronicles'] },
  { n: 15, file: 'ezra',            name: 'Ezra',            testament: 'OT', aliases: ['ezr'] },
  { n: 16, file: 'nehemiah',        name: 'Nehemiah',        testament: 'OT', aliases: ['neh', 'ne'] },
  { n: 17, file: 'esther',          name: 'Esther',          testament: 'OT', aliases: ['esth', 'est', 'es'] },
  { n: 18, file: 'job',             name: 'Job',             testament: 'OT', aliases: ['jb'] },
  { n: 19, file: 'psalms',          name: 'Psalms',          testament: 'OT', aliases: ['psalm', 'ps', 'psa', 'pss'] },
  { n: 20, file: 'proverbs',        name: 'Proverbs',        testament: 'OT', aliases: ['prov', 'pro', 'prv', 'pr'] },
  { n: 21, file: 'ecclesiastes',    name: 'Ecclesiastes',    testament: 'OT', aliases: ['eccl', 'ecc', 'ec', 'qoheleth'] },
  { n: 22, file: 'songofsolomon',   name: 'Song of Solomon', testament: 'OT', aliases: ['song of songs', 'song', 'sos', 'canticles', 'ss'] },
  { n: 23, file: 'isaiah',          name: 'Isaiah',          testament: 'OT', aliases: ['isa', 'is'] },
  { n: 24, file: 'jeremiah',        name: 'Jeremiah',        testament: 'OT', aliases: ['jer', 'je'] },
  { n: 25, file: 'lamentations',    name: 'Lamentations',    testament: 'OT', aliases: ['lam', 'la'] },
  { n: 26, file: 'ezekiel',         name: 'Ezekiel',         testament: 'OT', aliases: ['ezek', 'eze', 'ezk'] },
  { n: 27, file: 'daniel',          name: 'Daniel',          testament: 'OT', aliases: ['dan', 'da', 'dn'] },
  { n: 28, file: 'hosea',           name: 'Hosea',           testament: 'OT', aliases: ['hos', 'ho'] },
  { n: 29, file: 'joel',            name: 'Joel',            testament: 'OT', aliases: ['jl'] },
  { n: 30, file: 'amos',            name: 'Amos',            testament: 'OT', aliases: ['am'] },
  { n: 31, file: 'obadiah',         name: 'Obadiah',         testament: 'OT', aliases: ['obad', 'ob'] },
  { n: 32, file: 'jonah',           name: 'Jonah',           testament: 'OT', aliases: ['jon', 'jnh'] },
  { n: 33, file: 'micah',           name: 'Micah',           testament: 'OT', aliases: ['mic', 'mc'] },
  { n: 34, file: 'nahum',           name: 'Nahum',           testament: 'OT', aliases: ['nah', 'na'] },
  { n: 35, file: 'habakkuk',        name: 'Habakkuk',        testament: 'OT', aliases: ['hab', 'hb'] },
  { n: 36, file: 'zephaniah',       name: 'Zephaniah',       testament: 'OT', aliases: ['zeph', 'zep', 'zp'] },
  { n: 37, file: 'haggai',          name: 'Haggai',          testament: 'OT', aliases: ['hag', 'hg'] },
  { n: 38, file: 'zechariah',       name: 'Zechariah',       testament: 'OT', aliases: ['zech', 'zec', 'zc'] },
  { n: 39, file: 'malachi',         name: 'Malachi',         testament: 'OT', aliases: ['mal', 'ml'] },
  { n: 40, file: 'matthew',         name: 'Matthew',         testament: 'NT', aliases: ['matt', 'mat', 'mt'] },
  { n: 41, file: 'mark',            name: 'Mark',            testament: 'NT', aliases: ['mrk', 'mk', 'mr'] },
  { n: 42, file: 'luke',            name: 'Luke',            testament: 'NT', aliases: ['luk', 'lk'] },
  { n: 43, file: 'john',            name: 'John',            testament: 'NT', aliases: ['jhn', 'jn'] },
  { n: 44, file: 'acts',            name: 'Acts',            testament: 'NT', aliases: ['act', 'ac', 'acts of the apostles'] },
  { n: 45, file: 'romans',          name: 'Romans',          testament: 'NT', aliases: ['rom', 'ro', 'rm'] },
  { n: 46, file: '1corinthians',    name: '1 Corinthians',   testament: 'NT', aliases: ['1 cor', '1cor', '1 co', 'i corinthians', 'first corinthians'] },
  { n: 47, file: '2corinthians',    name: '2 Corinthians',   testament: 'NT', aliases: ['2 cor', '2cor', '2 co', 'ii corinthians', 'second corinthians'] },
  { n: 48, file: 'galatians',       name: 'Galatians',       testament: 'NT', aliases: ['gal', 'ga'] },
  { n: 49, file: 'ephesians',       name: 'Ephesians',       testament: 'NT', aliases: ['eph', 'ephes'] },
  { n: 50, file: 'philippians',     name: 'Philippians',     testament: 'NT', aliases: ['phil', 'php', 'pp'] },
  { n: 51, file: 'colossians',      name: 'Colossians',      testament: 'NT', aliases: ['col', 'co'] },
  { n: 52, file: '1thessalonians',  name: '1 Thessalonians', testament: 'NT', aliases: ['1 thess', '1thess', '1 th', 'i thessalonians', 'first thessalonians'] },
  { n: 53, file: '2thessalonians',  name: '2 Thessalonians', testament: 'NT', aliases: ['2 thess', '2thess', '2 th', 'ii thessalonians', 'second thessalonians'] },
  { n: 54, file: '1timothy',        name: '1 Timothy',       testament: 'NT', aliases: ['1 tim', '1tim', '1 ti', 'i timothy', 'first timothy'] },
  { n: 55, file: '2timothy',        name: '2 Timothy',       testament: 'NT', aliases: ['2 tim', '2tim', '2 ti', 'ii timothy', 'second timothy'] },
  { n: 56, file: 'titus',           name: 'Titus',           testament: 'NT', aliases: ['tit', 'ti'] },
  { n: 57, file: 'philemon',        name: 'Philemon',        testament: 'NT', aliases: ['phlm', 'phm', 'pm'] },
  { n: 58, file: 'hebrews',         name: 'Hebrews',         testament: 'NT', aliases: ['heb'] },
  { n: 59, file: 'james',           name: 'James',           testament: 'NT', aliases: ['jas', 'jm'] },
  { n: 60, file: '1peter',          name: '1 Peter',         testament: 'NT', aliases: ['1 pet', '1pet', '1 pe', '1 pt', 'i peter', 'first peter'] },
  { n: 61, file: '2peter',          name: '2 Peter',         testament: 'NT', aliases: ['2 pet', '2pet', '2 pe', '2 pt', 'ii peter', 'second peter'] },
  { n: 62, file: '1john',           name: '1 John',          testament: 'NT', aliases: ['1 jn', '1jn', '1 jo', 'i john', 'first john'] },
  { n: 63, file: '2john',           name: '2 John',          testament: 'NT', aliases: ['2 jn', '2jn', '2 jo', 'ii john', 'second john'] },
  { n: 64, file: '3john',           name: '3 John',          testament: 'NT', aliases: ['3 jn', '3jn', '3 jo', 'iii john', 'third john'] },
  { n: 65, file: 'jude',            name: 'Jude',            testament: 'NT', aliases: ['jud', 'jd'] },
  { n: 66, file: 'revelation',      name: 'Revelation',      testament: 'NT', aliases: ['rev', 're', 'the revelation', 'revelation of john', 'apocalypse'] },
];
